### ISSUE TITLE
Source files for Resource tests are in the incorrect directory / package

### ISSUE THREAD

**Issue by briansurratt** [Logiraptor/concourse-dsl#14]
The source files for the Resource implementations are located in 

`src/main/kotlin/io/poyarzun/concoursedsl/resources/`

but the tests are in

`src/test/kotlin/io/poyarzun/concoursedsl/dsl/resources/`

The tests should be in 

`src/test/kotlin/io/poyarzun/concoursedsl/resources/`

**Comment by Logiraptor** [comment]
This seems reasonable enough. Feel free to send a PR.

**Comment by Logiraptor** [comment]
Fixed by #16
