### ISSUE TITLE
Implement type-safe support for the semver resource

### ISSUE THREAD

**Issue by Logiraptor** [Logiraptor/concourse-dsl#6]
Take inspiration from the GitResource

Fields are documented here:

https://github.com/concourse/semver-resource

**Comment by briansurratt** [comment]
Started working on this, ran into a snag.  This made me realize that testing a pipeline `fly vp` isn't really enough to validate it.   There will need to be a feedback loop of other folks using and testing these Resource implementations.

**Comment by Logiraptor** [comment]
@briansurratt Can you help me understand what the snag is? I agree that the best feedback is from real use. is there something specific that makes this resource special?

**Comment by briansurratt** [comment]
The snag was a mistake on my part, not fully reading the spec before getting started.  As a result, my data classes for the source parameters weren't set up correctly.  I have addressed that and will have a pull request ready shortly.

**Comment by briansurratt** [comment]
I think this resource is more tricky because it supports a number of different persistence methods (git, GCS,  Amazon S3, etc).  I could test the git implementation but would need someone else to validate the others.
